### ISSUE TITLE
How to run this script?

### ISSUE THREAD

**Issue by kandangjamur** [MTN718/bybit_bot#1]
I restore the sql file, put db credential, bybit apikey and telegram bot token, and try to run bybit.php script as cron job. but no return. can you please tell me how to run this?

**Comment by MTN718** [comment]
you can see log file, api response store in log file if you installed correctly

**Comment by kandangjamur** [comment]
Hi @MTN718 , thanks for the response.
seems like me not installed it correctly, can you please tell me how to install it correctly? and what interval to set for cron job?

Thanks
